# Generated by Django 5.0.6 on 2024-05-25 13:50

import data_pusher_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pusher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.UUIDField(default=data_pusher_app.models.generate_app_secret_token, editable=False, unique=True),
        ),
    ]
